const mockData = {
  student: {
    id: "11259001",
    name: "林語安",
    department: "北科大 資訊與財金管理系",
    verified: true,
    rentPaid: true,
    repairProgress: ["已讀", "派工中", "已完修"],
    currentRepairStep: 1
  },
  properties: [
    {
      id: 1,
      title: "新生南路採光雅房",
      district: "大安區",
      type: "雅房",
      price: 7200,
      subsidy: true,
      mrtDistance: 6,
      rooms: 1,
      size: 7,
      x: 58,
      y: 37,
      landlord: "王先生",
      verified: true,
      terms: ["獨立電表", "一度電 5 元", "可租補", "近北科大"],
      description: "步行到校約 9 分鐘，採光明亮，公共區域每週固定清潔。"
    },
    {
      id: 2,
      title: "忠孝新生電梯套房",
      district: "中正區",
      type: "套房",
      price: 11800,
      subsidy: true,
      mrtDistance: 3,
      rooms: 1,
      size: 10,
      x: 47,
      y: 43,
      landlord: "林小姐",
      verified: true,
      terms: ["獨立電表", "管理室", "公版合約", "可租補"],
      description: "捷運出口旁，附基本家具，合約採內政部公版條款。"
    },
    {
      id: 3,
      title: "八德路雙人分租宅",
      district: "大安區",
      type: "分租",
      price: 9600,
      subsidy: false,
      mrtDistance: 11,
      rooms: 2,
      size: 16,
      x: 70,
      y: 30,
      landlord: "張先生",
      verified: true,
      terms: ["公共電費均分", "垃圾代收", "不可寵物"],
      description: "適合兩位同學合租，客廳寬敞，位於北科大生活圈內。"
    },
    {
      id: 4,
      title: "台電大樓安靜套房",
      district: "大安區",
      type: "套房",
      price: 10800,
      subsidy: true,
      mrtDistance: 8,
      rooms: 1,
      size: 9,
      x: 38,
      y: 63,
      landlord: "陳太太",
      verified: true,
      terms: ["一度電 5 元", "獨立衛浴", "可租補"],
      description: "巷弄安靜，近超商與自助洗衣，適合研究生長期居住。"
    },
    {
      id: 5,
      title: "萬華老宅整層出租",
      district: "萬華區",
      type: "整層",
      price: 15000,
      subsidy: false,
      mrtDistance: 14,
      rooms: 3,
      size: 28,
      x: 24,
      y: 46,
      landlord: "周先生",
      verified: false,
      terms: ["押金兩個月", "待補權狀", "可開伙"],
      description: "空間大但尚待平台完成權狀核對，Demo 中可作為風險對照。"
    },
    {
      id: 6,
      title: "光華商圈小資套房",
      district: "中正區",
      type: "套房",
      price: 9200,
      subsidy: true,
      mrtDistance: 7,
      rooms: 1,
      size: 8,
      x: 51,
      y: 50,
      landlord: "劉小姐",
      verified: true,
      terms: ["獨立電表", "公版合約", "可租補"],
      description: "近光華商場與校園，生活機能完整，適合預算有限的新生。"
    },
    {
      id: 7,
      title: "華山旁女生雅房",
      district: "中正區",
      type: "雅房",
      price: 6800,
      subsidy: false,
      mrtDistance: 9,
      rooms: 1,
      size: 6,
      x: 43,
      y: 35,
      landlord: "蔡太太",
      verified: true,
      terms: ["公共電費均分", "垃圾代收", "不可寵物"],
      description: "公共區域明亮，限女生入住，房東住附近可即時協助。"
    },
    {
      id: 8,
      title: "南京復興兩房合租",
      district: "中山區",
      type: "分租",
      price: 9800,
      subsidy: true,
      mrtDistance: 5,
      rooms: 2,
      size: 18,
      x: 74,
      y: 42,
      landlord: "何先生",
      verified: true,
      terms: ["獨立電表", "可租補", "公版合約"],
      description: "適合兩位同學一起分租，鄰近大安與中山交界，通勤到北科大方便。"
    },
    {
      id: 9,
      title: "古亭靜巷研究生套房",
      district: "大安區",
      type: "套房",
      price: 12500,
      subsidy: true,
      mrtDistance: 10,
      rooms: 1,
      size: 11,
      x: 34,
      y: 70,
      landlord: "郭小姐",
      verified: true,
      terms: ["一度電 5 元", "獨立衛浴", "可開伙", "可租補"],
      description: "巷內安靜，書桌與收納完整，適合準備研究所或專題的學生。"
    },
    {
      id: 10,
      title: "西門町電梯小套",
      district: "萬華區",
      type: "套房",
      price: 8200,
      subsidy: false,
      mrtDistance: 6,
      rooms: 1,
      size: 7,
      x: 20,
      y: 56,
      landlord: "許先生",
      verified: true,
      terms: ["管理室", "獨立電表", "押金兩個月"],
      description: "捷運與公車選擇多，租金較低，適合重視交通彈性的學生。"
    },
    {
      id: 11,
      title: "永康街質感整層",
      district: "大安區",
      type: "整層",
      price: 15800,
      subsidy: true,
      mrtDistance: 12,
      rooms: 2,
      size: 21,
      x: 39,
      y: 55,
      landlord: "賴小姐",
      verified: true,
      terms: ["公版合約", "可租補", "獨立電表", "可開伙"],
      description: "兩房一廳，適合已媒合成功的室友共同承租。"
    },
    {
      id: 12,
      title: "民生社區採光雅房",
      district: "中山區",
      type: "雅房",
      price: 6500,
      subsidy: true,
      mrtDistance: 13,
      rooms: 1,
      size: 6,
      x: 82,
      y: 25,
      landlord: "沈太太",
      verified: true,
      terms: ["可租補", "公共電費均分", "垃圾代收"],
      description: "環境單純，公共空間清爽，房東接受學生租補文件需求。"
    },
    {
      id: 15,
      title: "建國南路低預算雅房",
      district: "大安區",
      type: "雅房",
      price: 6200,
      subsidy: true,
      mrtDistance: 5,
      rooms: 1,
      size: 5,
      x: 55,
      y: 49,
      landlord: "李小姐",
      verified: true,
      terms: ["可租補", "公共電費均分", "垃圾代收"],
      description: "北科大旁低預算雅房，適合新生先求通勤方便與租金穩定。"
    },
    {
      id: 16,
      title: "復興南路學生套房",
      district: "大安區",
      type: "套房",
      price: 9800,
      subsidy: true,
      mrtDistance: 6,
      rooms: 1,
      size: 8,
      x: 61,
      y: 54,
      landlord: "吳先生",
      verified: true,
      terms: ["獨立電表", "公版合約", "可租補"],
      description: "走路可到北科大，獨立衛浴與簡易書桌，適合重視隱私的學生。"
    },
    {
      id: 17,
      title: "濟南路雙人分租房",
      district: "大安區",
      type: "分租",
      price: 7800,
      subsidy: false,
      mrtDistance: 7,
      rooms: 2,
      size: 13,
      x: 49,
      y: 46,
      landlord: "宋太太",
      verified: true,
      terms: ["公共電費均分", "不可寵物", "公版合約"],
      description: "兩間房可分租，公共客廳小但離學校很近，適合已有室友者。"
    },
    {
      id: 18,
      title: "和平東路小整層",
      district: "大安區",
      type: "整層",
      price: 14500,
      subsidy: true,
      mrtDistance: 10,
      rooms: 2,
      size: 17,
      x: 46,
      y: 66,
      landlord: "高先生",
      verified: true,
      terms: ["可租補", "獨立電表", "可開伙", "公版合約"],
      description: "兩人合租剛好，換算每人約七千多，適合學生共同承租。"
    },
    {
      id: 19,
      title: "杭州南路雅房",
      district: "中正區",
      type: "雅房",
      price: 6000,
      subsidy: true,
      mrtDistance: 8,
      rooms: 1,
      size: 5,
      x: 40,
      y: 48,
      landlord: "葉小姐",
      verified: true,
      terms: ["可租補", "公共電費均分", "垃圾代收"],
      description: "中正區靠近北科大，租金低，房東願意配合租補文件。"
    },
    {
      id: 20,
      title: "善導寺合租整層",
      district: "中正區",
      type: "整層",
      price: 15000,
      subsidy: false,
      mrtDistance: 6,
      rooms: 2,
      size: 18,
      x: 36,
      y: 36,
      landlord: "方先生",
      verified: true,
      terms: ["公版合約", "獨立電表", "可開伙"],
      description: "兩房整層，兩人分攤後單人租金落在學生可接受範圍。"
    },
    {
      id: 21,
      title: "吉林路平價套房",
      district: "中山區",
      type: "套房",
      price: 9200,
      subsidy: true,
      mrtDistance: 9,
      rooms: 1,
      size: 7,
      x: 68,
      y: 47,
      landlord: "馬小姐",
      verified: true,
      terms: ["可租補", "獨立衛浴", "一度電 5 元"],
      description: "中山區平價套房，公車到北科大方便，生活機能完整。"
    },
    {
      id: 22,
      title: "中山國小雙人分租",
      district: "中山區",
      type: "分租",
      price: 7600,
      subsidy: true,
      mrtDistance: 12,
      rooms: 2,
      size: 14,
      x: 76,
      y: 58,
      landlord: "杜先生",
      verified: true,
      terms: ["可租補", "公共電費均分", "垃圾代收"],
      description: "雙人分租，每間都有窗，適合想壓低租金的學生。"
    },
    {
      id: 23,
      title: "中山站小整層",
      district: "中山區",
      type: "整層",
      price: 15500,
      subsidy: true,
      mrtDistance: 11,
      rooms: 2,
      size: 16,
      x: 73,
      y: 38,
      landlord: "范小姐",
      verified: true,
      terms: ["可租補", "公版合約", "獨立電表"],
      description: "兩房小整層，適合室友媒合成功後共同承租。"
    },
    {
      id: 24,
      title: "艋舺平價雅房",
      district: "萬華區",
      type: "雅房",
      price: 5600,
      subsidy: false,
      mrtDistance: 14,
      rooms: 1,
      size: 5,
      x: 12,
      y: 52,
      landlord: "鐘太太",
      verified: true,
      terms: ["公共電費均分", "垃圾代收", "押金兩個月"],
      description: "租金最低的一批房源，適合預算非常有限、可接受稍長通勤者。"
    },
    {
      id: 25,
      title: "西門合租分租房",
      district: "萬華區",
      type: "分租",
      price: 7000,
      subsidy: true,
      mrtDistance: 9,
      rooms: 2,
      size: 12,
      x: 22,
      y: 42,
      landlord: "白先生",
      verified: true,
      terms: ["可租補", "公共電費均分", "公版合約"],
      description: "兩位學生分租，交通選擇多，房東已完成平台驗證。"
    },
    {
      id: 26,
      title: "青年公園小整層",
      district: "萬華區",
      type: "整層",
      price: 13200,
      subsidy: true,
      mrtDistance: 15,
      rooms: 2,
      size: 17,
      x: 18,
      y: 76,
      landlord: "鄧小姐",
      verified: true,
      terms: ["可租補", "可開伙", "獨立電表"],
      description: "距離較遠但租金低，兩人分攤後很適合學生族群。"
    },
    {
      id: 13,
      title: "善導寺短租套房",
      district: "中正區",
      type: "套房",
      price: 9000,
      subsidy: false,
      mrtDistance: 4,
      rooms: 1,
      size: 8,
      x: 45,
      y: 26,
      landlord: "楊先生",
      verified: true,
      terms: ["獨立電表", "短租可談", "公版合約"],
      description: "適合交換生或短期實習，離學校與台北車站都近。"
    },
    {
      id: 14,
      title: "龍山寺整修套房",
      district: "萬華區",
      type: "套房",
      price: 7600,
      subsidy: true,
      mrtDistance: 12,
      rooms: 1,
      size: 8,
      x: 16,
      y: 67,
      landlord: "潘小姐",
      verified: true,
      terms: ["可租補", "獨立衛浴", "一度電 5 元"],
      description: "近期重新粉刷，租金低於市中心行情，適合省預算。"
    },
    {
      id: 27,
      title: "臨沂街雙人分租",
      district: "中正區",
      type: "分租",
      price: 7400,
      subsidy: true,
      mrtDistance: 5,
      rooms: 2,
      size: 12,
      x: 42,
      y: 42,
      landlord: "任先生",
      verified: true,
      terms: ["可租補", "公共電費均分", "公版合約"],
      description: "靠近北科大與捷運站，兩位學生分租後負擔低。"
    }
  ],
  roommateCandidates: [
    { id: 1, name: "許庭瑄", department: "互動設計系", sleep: "late", noise: "medium", clean: "weekly", guest: "ask", split: "equal", pet: "no", note: "喜歡夜間讀書，公共空間固定週日整理。" },
    { id: 2, name: "黃以辰", department: "資訊工程系", sleep: "early", noise: "low", clean: "daily", guest: "rare", split: "meter", pet: "no", note: "作息穩定，重視安靜與清潔。" },
    { id: 3, name: "吳品妤", department: "工業設計系", sleep: "late", noise: "low", clean: "weekly", guest: "ask", split: "equal", pet: "cat", note: "偶爾接案到晚，能接受事前溝通訪客。" },
    { id: 4, name: "鄭凱翔", department: "電機工程系", sleep: "early", noise: "medium", clean: "weekly", guest: "rare", split: "equal", pet: "no", note: "習慣輪值打掃，預算控管明確。" },
    { id: 5, name: "陳若晴", department: "經營管理系", sleep: "early", noise: "low", clean: "weekly", guest: "ask", split: "meter", pet: "no", note: "平日早起，能接受偶爾朋友來訪但希望先說好。" },
    { id: 6, name: "林冠宇", department: "建築系", sleep: "late", noise: "medium", clean: "daily", guest: "ask", split: "equal", pet: "cat", note: "常做模型到晚，願意每天整理公共桌面。" },
    { id: 7, name: "謝孟蓁", department: "工管系", sleep: "early", noise: "low", clean: "daily", guest: "rare", split: "equal", pet: "no", note: "生活規律，偏好低干擾、低訪客的合租環境。" },
    { id: 8, name: "羅子恩", department: "資財系", sleep: "late", noise: "low", clean: "weekly", guest: "rare", split: "meter", pet: "no", note: "晚睡但會戴耳機，重視電費照表分攤。" },
    { id: 9, name: "張雅筑", department: "應英系", sleep: "early", noise: "medium", clean: "weekly", guest: "ask", split: "equal", pet: "cat", note: "可接受貓，偏好事前溝通公共規則。" },
    { id: 10, name: "邱柏叡", department: "車輛工程系", sleep: "late", noise: "medium", clean: "daily", guest: "rare", split: "meter", pet: "no", note: "常晚歸，願意用分表或紀錄方式分攤耗材與電費。" }
  ],
  landlord: {
    name: "王柏翰",
    reviewStatus: "黑名單未命中，權狀待平台核對",
    todos: [
      { id: 1, text: "忠孝新生 301：本月租金未繳", type: "rent", urgent: true },
      { id: 2, text: "新生南路 5F：浴室漏水報修", type: "repair", urgent: true },
      { id: 3, text: "八德路 2F：合約 7 天後到期", type: "contract", urgent: false }
    ],
    rooms: [
      { id: 1, room: "301", tenant: "林語安", rent: "未繳", repair: "派工中" },
      { id: 2, room: "502", tenant: "黃以辰", rent: "已繳", repair: "無" },
      { id: 3, room: "2F-A", tenant: "許庭瑄", rent: "未繳", repair: "待讀取" }
    ]
  },
  admin: {
    reviewCases: [
      { id: 1, landlord: "王柏翰", idCheck: "通過", deedCheck: "待核對", blacklist: false, status: "待審核" },
      { id: 2, landlord: "周明德", idCheck: "通過", deedCheck: "疑似不符", blacklist: true, status: "凍結" },
      { id: 3, landlord: "林采潔", idCheck: "通過", deedCheck: "通過", blacklist: false, status: "可發標章" }
    ],
    disputes: [
      {
        id: "D-2026-014",
        title: "浴室漏水逾兩週未完修",
        tenant: "林語安",
        landlord: "王柏翰",
        status: "平台介入中",
        footprints: ["2026/05/28 租客上傳漏水照片", "2026/05/29 房東已讀並回覆派工", "2026/06/06 工班改期", "2026/06/12 租客申請平台介入"]
      }
    ]
  },
  knowledge: {
    "獨立電表": "每戶用電獨立計算，比較能避免與其他租客分攤不明電費。",
    "一度電 5 元": "指每 kWh 電費 5 元。可和台電級距比較，確認是否高於合理行情。",
    "公版合約": "採內政部住宅租賃定型化契約，能降低不合理條款風險。",
    "押金兩個月": "一般押金不得超過兩個月租金，超過時平台會標記異常。"
  }
};
